### ISSUE TITLE
Skills to Reset Faster Relative to Time Stop

### ISSUE THREAD

**Issue by isteals** [PotatoFaceJames/HtHCVR#16]
got stuck waiting on a timer for timestop once

**Comment by PotatoFaceJames** [comment]
This is when you activate skills in time stop. Maybe I'll just put a check that always gives you the ability back, but for now this isn't a bug

**Comment by isteals** [comment]
so worst case scenario is if you accidentally activate one of your skills while in timestop, you could potentially get stuck in timestop for a week.
