### ISSUE TITLE
swords float in mid air

### ISSUE THREAD

**Issue by isteals** [PotatoFaceJames/HtHCVR#19]
sometimes swords you drop (not enemy ones i dont think) stay floating in mid air without being removed from map

**Comment by PotatoFaceJames** [comment]
What are you doing to reproduce this?
![image](https://user-images.githubusercontent.com/47709023/68450312-3ac3be00-01b0-11ea-8372-ccaf0525b1aa.png)

**Comment by isteals** [comment]
spawn twice in quick succession with the same hand. the second sword floats

**Comment by isteals** [comment]
![image](https://user-images.githubusercontent.com/57417688/68549014-67174e80-03eb-11ea-91d5-70ac121fad4d.png)

**Comment by isteals** [comment]
![image](https://user-images.githubusercontent.com/57417688/68549526-c461ce80-03f0-11ea-8277-7b0f77e06aab.png)

**Comment by isteals** [comment]
![image](https://user-images.githubusercontent.com/57417688/68549533-d2afea80-03f0-11ea-8310-c07990bab106.png)

**Comment by isteals** [comment]
![image](https://user-images.githubusercontent.com/57417688/68549701-11df3b00-03f3-11ea-81fc-ddf5817ee68c.png)
