### ISSUE TITLE
Flying Perk Stuck No Jump

### ISSUE THREAD

**Issue by isteals** [PotatoFaceJames/HtHCVR#30]
i purchased the ability for the first time. for a second i flew in the air, from then on i couldnt fly or jump. if i pressed jump it kick my left knee out slightly and not do much more. had to reset my save to fix,same issue next time i bought the skill, il avoid for now)

**Comment by PotatoFaceJames** [comment]
Yeah I had notified you about this bug previously I'm pretty sure
