### ISSUE TITLE
Tutorial Gestures Clumping

### ISSUE THREAD

**Issue by isteals** [PotatoFaceJames/HtHCVR#31]
(reset save) purchased some abilities and the demo animations were playing on top of each other. could be improved. not sure of best resolution to this

**Comment by isteals** [comment]
![image](https://user-images.githubusercontent.com/57417688/68549746-90d47380-03f3-11ea-8e4a-021cc85286c8.png)

**Comment by PotatoFaceJames** [comment]
It should be destroying the new one, but buying skills isn't probably the best name for this
